//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejercicio_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Course_Student = new HashSet<Course_Student>();
        }
    
        public int Id_Course { get; set; }
        public string Name_Course { get; set; }
        public Nullable<System.TimeSpan> Time_Course { get; set; }
        public string Day { get; set; }
        public Nullable<int> Id_Teacher { get; set; }
        public Nullable<int> Maximun_Number_Of_Students { get; set; }
        public string Detail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Student> Course_Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
