//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejercicio_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patent_Family
    {
        public int Id_Role { get; set; }
        public Nullable<int> Id_Family { get; set; }
        public Nullable<int> Id_Patent { get; set; }
    
        public virtual Family Family { get; set; }
        public virtual Patent Patent { get; set; }
    }
}
