//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejercicio_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Course_Student = new HashSet<Course_Student>();
        }
    
        public int Id_Student { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> Docket { get; set; }
        public Nullable<int> National_Identity_Document { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> IdFamilia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Student> Course_Student { get; set; }
        public virtual Family Family { get; set; }
    }
}
